EN_WORDS = [
    "network", "cyberspace", "google", "computer network", "youtube", "facebook", "online", "world wide web",
    "web browser", "social", "phone", "cable", "media", "data", "digital", "websites", "email",
    "computer", "intranet", "link", "information", "website", "database", "wifi", "social networking",
    "wireless", "offline", "messaging", "microsoft", "multimedia", "cyber", "technology", "ip address", "game",
    "browser", "laptop", "chatrooms", "reddit", "modem", "search engine", "chat", "blogging", "connection",
    "communications", "cell", "computers", "hyperlink", "webcam", "news", "myspace", "youtube",
    "search engines", "business", "tech", "twitter", "electronic", "virtual", "engineering", "power",
    "advertising", "newsgroup", "web surfers", "protocol", "web site", "supercomputer", "networking",
    "hypertext", "watching", "allows", "cybersociology", "data process", "internet telephony", "networks",
    "streaming", "text messaging", "web page", "hypertext", "electric", "online shopping", "blog", "society",
    "amazon", "login", "world", "server", "peer-to-peer", "utilities", "social network service",
    "ethernet", "people", "friends", "servers", "bittorrent", "gaming", "podcast", "cable modems", "street",
    "cellphones", "desktop", "downloads",
    "applications", "predictor", "marketplace", "supply chain", "netlag", "computerologist", "webpages",
    "homepage", "mobile telephony", "cern", "file sharing", "internet", "video", "phones", "telephony",
    "tim berners-lee", "telephone", "other", "device", "cellular", "web server", "games", "e commerce",
    "smartphone", "cellphone", "hardware", "service", "party", "apps", "public", "television", "mobile",
    "telecom", "ping", "texting", "communication", "world wide", "customer", "fandom", "machine", "modern",
    "tiktok", "signal", "instagram", "real", "culture", "fiber", "influencer", "landline", "screen", "mail",
    "ip addresses", "external", "firewall", "government", "wikipedia", "internetwork", "internetworking",
    "podcasting", "user", "subscribers", "provider", "addresses", "interactive", "content", "readers",
    "informatics", "tracking", "messages", "clients", "wired", "hotspot", "cybersuicide", "proper noun",
    "telecomputer", "hotmail", "stream video", "nanocomputer", "computercide", "data path", "hacker", "ascii",
    "geocities", "broadband internet access", "optical fiber", "connect to internet", "satellite internet",
    "internet cafe", "log on", "digital library", "social networking sites", "meme", "cloud", "smart",
    "webmail", "text", "internet cafes", "smartphones", "memes", "radio", "book", "software",
    "wireless broadband", "home", "office", "devices", "cell phones", "local area network", "attention",
    "dating", "local", "work", "influencers", "web browsers", "vpn", "celebrity", "twitch", "watch", "calls",
    "yahoo", "access", "money", "telecommunications", "library", "protocol", "net", "webpage", "forums", "grid",
    "reception", "academic", "users", "publish", "messaging", "sites", "search", "customers", "connections",
    "web application", "enables", "available", "instant", "travel", "selling", "companies", "outlets",
    "corporate", "focusing", "personal computer", "webcast", "financial services", "emails", "cyberinteraction",
    "wiki", "multinetworked", "microcomputer", "motherboard", "microprocessor", "safari", "downloader",
    "teleprocessing", "keyword", "audience", "softmodem", "cost", "transputer", "telelearning", "rootkit",
    "computerdom", "puter", "internet acces"
]
